<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Users Report</title>
</head>
<body>
<div style="margin-bottom:25px;"><strong>Report generated by: </strong></div>
<table style="border-collapse: collapse;">
    <thead>
    <tr>

        <th style="border-bottom:2pt solid black;">
            <strong>Nom</strong>
        </th>
        <th style="border-bottom:2pt solid black;">
            <strong>Reeference</strong>
        </th>
    </tr>
    </thead>
    <tbody>
    @foreach ($articles as $art)
        <tr>

            <td style="border-bottom:1pt solid black;">
                {{$art->nom}}
            </td>
            <td style="border-bottom:1pt solid black;">
                {{$art->reference}}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>
</body>
</html>
